{
 "title": "crypto_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "coin",
    "query": {
     "query": "label_values(crypto_price_usd,symbol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "90-percentile 6h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "quantile_over_time(0.9, crypto_price_usd{symbol=\"$coin\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Средняя цена топ-5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(crypto_price_usd{symbol=~\"BTC|ETH|SOL|DOGE|ADA\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BTC_high",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(crypto_price_usd{symbol=\"BTC\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24h Change (BTC)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_price_change_24h_percent{symbol=\"BTC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG_price of chosen token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg_over_time(crypto_price_usd{symbol=\"$coin\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Market Cap (BTC)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_market_cap_usd{symbol=\"BTC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volatility 6h (σ)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev_over_time(crypto_price_usd{symbol=\"$coin\"}[6h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solana (USD)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_price_usd{symbol=\"SOL\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Торговый объём (BTC)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "crypto_volume_24h_usd{symbol=\"BTC\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bitcoin (USD)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_price_usd{symbol=\"BTC\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "24h Change (ETH)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_price_change_24h_percent{symbol=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Market Cap (ETH)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_market_cap_usd{symbol=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dogecoin (USD)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_price_usd{symbol=\"DOGE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum (USD)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crypto_price_usd{symbol=\"ETH\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}